// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm9MaZvk8pbs8lxLwfDWqfC1a3kYYU0IU',
    appId: '1:581139140913:web:637a1ae9deca6a3072a010',
    messagingSenderId: '581139140913',
    projectId: 'bookstore-b1781',
    authDomain: 'bookstore-b1781.firebaseapp.com',
    storageBucket: 'bookstore-b1781.firebasestorage.app',
    measurementId: 'G-ZHX4B8639E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2wmu2qTIcE90gd_2BPgc_9QuI6_Za2a4',
    appId: '1:581139140913:android:d6c90e288d3637a072a010',
    messagingSenderId: '581139140913',
    projectId: 'bookstore-b1781',
    storageBucket: 'bookstore-b1781.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdKFKtr7dLYK35FdQVN_qVwWTuw-M4S7A',
    appId: '1:581139140913:ios:62ef61f1e96d3a8c72a010',
    messagingSenderId: '581139140913',
    projectId: 'bookstore-b1781',
    storageBucket: 'bookstore-b1781.firebasestorage.app',
    iosClientId: '581139140913-92h725obgoo1j41ejlh4ne4rce56brbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdKFKtr7dLYK35FdQVN_qVwWTuw-M4S7A',
    appId: '1:581139140913:ios:62ef61f1e96d3a8c72a010',
    messagingSenderId: '581139140913',
    projectId: 'bookstore-b1781',
    storageBucket: 'bookstore-b1781.firebasestorage.app',
    iosClientId: '581139140913-92h725obgoo1j41ejlh4ne4rce56brbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm9MaZvk8pbs8lxLwfDWqfC1a3kYYU0IU',
    appId: '1:581139140913:web:54f8000c2aab0e1372a010',
    messagingSenderId: '581139140913',
    projectId: 'bookstore-b1781',
    authDomain: 'bookstore-b1781.firebaseapp.com',
    storageBucket: 'bookstore-b1781.firebasestorage.app',
    measurementId: 'G-26MGSXR9L9',
  );
}
